# Generated by Django 4.0.3 on 2022-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='numVotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='averageRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='tconst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
