# Generated by Django 4.0.3 on 2022-09-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ratings_numvotes_alter_ratings_averagerating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='moviess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.movies'),
        ),
    ]
